<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="PWII_Tugas 2_201401042.xsl"?>
<!DOCTYPE steamstore[
<!ELEMENT steamstore (game+)>
<!ELEMENT game (name, developer*, publisher, release_date, genre*, cover, links+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT developer (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT release_date (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT cover (#PCDATA)>
<!ELEMENT links (video*, image*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT image (#PCDATA)>
]>
<steamstore>
    <game>
        <name>Tales of Arise</name>
        <developer>BANDAI NAMCO Studios Inc.</developer>
        <publisher>BANDAI NAMCO Entertainment</publisher>
        <release_date>10 Sep, 2021</release_date>
        <genre uri="Anime" subject="Upcoming_video_games_related_to_anime_and_manga" wiki="List_of_anime_based_on_video_games">Anime</genre>
        <genre uri="JRPG" wiki="Japanese_role-playing_video_games">JRPG</genre>
        <genre uri="Role-playing_video_game" wiki="Action_role-playing_game">RPG</genre>
        <genre uri="Action-adventure_game" wiki="Action_role-playing">Action</genre>
        <genre>Action RPG</genre>
        <cover>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/header.jpg?t=1632698351</cover>
        <links>
            <video>https://www.youtube.com/embed/2g3XPcVSX_A</video>
            <video>https://www.youtube.com/embed/iGdJ4O_olBE</video>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_ff3e713e134572734fdc55adcb6043e2652f0506.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_3ca8447106ddb23b14e4e30db0b24cbb359e2a5f.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_7f7362042aff89d16cdf36c58b8c5674deb71d63.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_f14d3e50d12061fee9afa2f46718bc0e0538d286.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_d3f44bb87db552da6f17bb31ba4144639b24ed2f.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_094fd9b7124a4b0c825275285cd77d05efceb306.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_a6d09916ccb77d803b52286e286ec1febd858c2c.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_174cddf17835d4ad476eb93d73170f34bed3b2c7.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_e78d998d11ccae5feace23bb68f956c23ce30864.600x338.jpg?t=1632698351</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/740130/ss_0c0a6c29ff48cd12a446b81d74837d6c34b6a430.600x338.jpg?t=1632698351</image>
        </links>
    </game>
    <game>
        <name>NARAKA: BLADEPOINT</name>
        <developer>24 Entertainment</developer>
        <publisher>NetEase Games Montr√©al</publisher>
        <release_date>12 Aug, 2021</release_date>
        <genre uri="Battle_royale_game" wiki="Battle_royal" subject="Battle_royale_games">Battle Royale</genre>
        <genre uri="Multiplayer_video_game">Multiplayer</genre>
        <genre uri="Martial_arts_video_games">Martial Arts</genre>
        <genre uri="Survival_game" wiki="Survival_video_games">Survival</genre>
        <cover>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/header.jpg?t=1632317911</cover>
        <links>
            <video>https://www.youtube.com/embed/rE5hD3eDs1Y</video>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/ss_78ffacb5991aea06b4ee636b1c4c816abfb2cbfa.600x338.jpg?t=1632317911</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/ss_06b5f6c1f31c3519e51a45f9101da47e161e40c0.600x338.jpg?t=1632317911</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/ss_ca5451eff8bb830fa8db1ed19d8cf9a8a0d77a71.1920x1080.jpg?t=1632317911</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/ss_ca5451eff8bb830fa8db1ed19d8cf9a8a0d77a71.1920x1080.jpg?t=1632317911</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/ss_9a07d1693f769ef0b95c3d9e5cf9264cc3dd06f5.1920x1080.jpg?t=1632317911</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/ss_f2394a04d16f0fb52195bd0d4ec2cce68ecdfe4f.600x338.jpg?t=1632317911</image>
        </links>
    </game>
    <game>
        <name>Grand Theft Auto V</name>
        <developer>Rockstar North</developer>
        <publisher>Rockstar North</publisher>
        <release_date>14 Apr, 2015</release_date>
        <genre uri="Open_world">Open World</genre>
        <genre uri="Action-adventure_game" wiki="Action_game">Action</genre>
        <genre uri="Multiplayer_video_game">Multiplayer</genre>
        <genre uri="Vehicle_simulation_games">Automobile Sim</genre>
        <cover>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg?t=1618856444</cover>
        <links>
            <video>https://www.youtube.com/embed/xQT-O1nMSBU</video>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_32aa18ab3175e3002217862dd5917646d298ab6b.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_2744f112fa060320d191a50e8b3a92441a648a56.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_da39c16db175f6973770bae6b91d411251763152.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_bd5db78286be0a7c6b2c62519099a9e27e6b06f3.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_b1a1cb7959d6a0e6fcb2d06ebf97a66c9055cef3.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_bc5fc79d3366c837372327717249a4887aa46d63.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_d2eb9d3e50f9e4cb8db37d2976990b3795da8187.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_bd944debbec9936769f6dfb39ee456ca605615e3.600x338.jpg?t=1618856444</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/271590/ss_66daaa8e0416b805ffb9a853235e21468d6b85bc.600x338.jpg?t=1618856444</image>
        </links>
    </game>
    <game>
        <name>Counter-Strike: Global Offensive</name>
        <developer>Valve</developer>
        <developer>Hidden Path Entertainment</developer>
        <publisher>Valve</publisher>
        <release_date>22 Aug, 2012</release_date>
        <genre uri="First-person_shooter" wiki="List_of_first-person_shooters">FPS</genre>
        <genre uri="Shooter_game" wiki="Shooter_video_games">Shooter</genre>
        <genre uri="Multiplayer_video_game">Multiplayer</genre>
        <genre uri="Esports" wiki="Esports" subject="Esports_games">Competitive</genre>
        <genre uri="Action-adventure_game" wiki="Action_game">Action</genre>
        <cover>https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg?t=1631908705</cover>
        <links>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_118cb022b9a43f70d2e5a2df7427f29088b6b191.600x338.jpg?t=1631908705</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_d196d945c6170e9cadaf67a6dea675bd5fa7a046.600x338.jpg?t=1631908705</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_8c9cce9a9dde7b9c020837dcbd4615efe6f77d66.600x338.jpg?t=1631908705</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_2b9e362287b509bb3864fa7bad654fe1fda0f7ed.600x338.jpg?t=1631908705</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_855c016cde14b7cec5c3d2523589b9054c030010.600x338.jpg?t=1631908705</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_34090867f1a02b6c17652ba9043e3f622ed985a9.600x338.jpg?t=1631908705</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_77215ea1b454c08a75351a74585a5b089142da3e.600x338.jpg?t=1631908705</image>
        </links>
    </game>
    <game>
        <name>Fall Guys: Ultimate Knockout</name>
        <developer>Mediatonic</developer>
        <publisher>Mediatonic</publisher>
        <release_date>4 Aug, 2020</release_date>
        <genre uri="Family-friendly">Family Friendly</genre>
        <genre uri="Party_game" wiki="List_of_party_video_games" subject="Party_video_games">Party Game</genre>
        <genre uri="Player_versus_player">PvP</genre>
        <cover>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/header.jpg?t=1630144986</cover>
        <links>
            <video>https://www.youtube.com/embed/pqpvBzCgJQM</video>
            <video>https://www.youtube.com/embed/Wj3dUvGLjNQ</video>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/ss_37d4c0cf1b5d0f28a5e5a1cb20d0b44edc9445d7.600x338.jpg?t=1630144986</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/ss_d0962033aeee0aa5c8ee2a77e090fea384e0ab99.600x338.jpg?t=1630144986</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/ss_80c00e2cc1169b7ccfd1601c0fbec686eef05289.600x338.jpg?t=1630144986</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/ss_561e6093c95d3a13068a2365bf69f97d0b1ae653.600x338.jpg?t=1630144986</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/ss_c412983a53eeeda70c22e768ca8208531a098976.600x338.jpg?t=1630144986</image>
            <image>https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/ss_808385c188b1dcd45776ddd236b12391de74eb5c.600x338.jpg?t=1630144986</image>
        </links>
    </game>
</steamstore>